# Generated by Django 4.1.5 on 2023-03-30 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of file')),
                ('path', models.FileField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Collaborative Divorce Resources', 'Collaborative Divorce Resources'), ('Collaborative Co-Parenting Mediation Resources', 'Collaborative Co-Parenting Mediation Resources'), ('Assessments and Screeners', 'Assessments and Screeners'), ('Consultation and Therapy Services', 'Consultation and Therapy Services'), ('Co-Parenting Mediation Program', 'Co-Parenting Mediation Program')], max_length=50, verbose_name='Title name')),
                ('url_title', models.CharField(max_length=100, verbose_name='Link title')),
                ('url', models.CharField(max_length=100, verbose_name='Url of link')),
            ],
            options={
                'verbose_name': 'Link',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title of post')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='URL')),
                ('post', models.TextField(verbose_name='Text of post')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 3, 30, 15, 19, 28, 345786), verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Your Name')),
                ('case', models.TextField(verbose_name='Your Case')),
                ('abuse_from_CPS_DCFS', models.CharField(choices=[('Substantiated', 'Substantiated abuse from CPS/DCFS'), ('Unsubstantiated', 'Unsubstantiated abuse from CPS/DCFS')], default='Substantiated abuse from CPS/DCFS', max_length=36, verbose_name='abuse from CPS/DCFS')),
                ('parental_alienation', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Yes', max_length=10, verbose_name='Parental Alienation Degree')),
                ('allegations', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Parental Alienation Allegations')),
                ('falsified', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='falsified of parental alienation')),
                ('duration', models.TextField(verbose_name='duration')),
                ('money', models.TextField(verbose_name='money')),
                ('left_broken', models.TextField(verbose_name='Left / Broken')),
                ('abuse_criteria', models.TextField(verbose_name='abuse criteria')),
                ('result', models.TextField(verbose_name='result')),
            ],
            options={
                'verbose_name': 'User Post',
                'verbose_name_plural': 'User Posts',
            },
        ),
    ]
