# Generated by Django 4.1.2 on 2022-12-23 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_link_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url_title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 13, 52, 13, 761487)),
        ),
    ]
