# Generated by Django 4.1.5 on 2023-05-17 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_videolink_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 22, 55, 11, 873962), verbose_name='Time'),
        ),
    ]
