# Generated by Django 4.1.2 on 2022-12-27 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_link_title_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonim', max_length=20)),
                ('post', models.TextField()),
            ],
            options={
                'verbose_name': 'User Post',
                'verbose_name_plural': 'User Posts',
            },
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(choices=[('Collaborative Divorce Resources', 'Collaborative Divorce Resources'), ('Collaborative Co-Parenting Mediation Resources', 'Collaborative Co-Parenting Mediation Resources'), ('Assessments and Screeners', 'Assessments and Screeners'), ('Consultation and Therapy Services', 'Consultation and Therapy Services'), ('Co-Parenting Mediation Program', 'Co-Parenting Mediation Program')], max_length=50, verbose_name='Title name'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Url of link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url_title',
            field=models.CharField(max_length=100, verbose_name='Link title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 11, 39, 7, 502565)),
        ),
    ]
