# Generated by Django 4.1.2 on 2022-12-27 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userpost_alter_link_title_alter_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 11, 47, 35, 163894)),
        ),
    ]
