# Generated by Django 4.1.4 on 2022-12-29 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 10, 32, 51, 798600)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
