# Generated by Django 4.1.4 on 2023-01-16 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_time_alter_userpost_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post',
        ),
        migrations.AddField(
            model_name='userpost',
            name='abuse_criteria',
            field=models.TextField(default='Substantiated abuse from CPS/DCFS', verbose_name='abuse criteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='abuse_from_CPS_DCFS',
            field=models.CharField(choices=[('Substantiated', 'Substantiated abuse from CPS/DCFS'), ('Unsubstantiated', 'Unsubstantiated abuse from CPS/DCFS')], default='Substantiated abuse from CPS/DCFS', max_length=36, verbose_name='abuse from CPS/DCFS'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='allegations',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='allegations of parental alienation'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='case',
            field=models.TextField(default='aaa', verbose_name='case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='duration',
            field=models.TextField(default='aaaa', verbose_name='duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='falsified',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='falsified of parental alienation'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='left_broken',
            field=models.TextField(default='aaa', verbose_name='left broken'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='money',
            field=models.TextField(default='aaaaaa', verbose_name='money'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='parental_alienation',
            field=models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Yes', max_length=10, verbose_name='Mild'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='result',
            field=models.TextField(default='aaaa', verbose_name='result'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 16, 28, 47, 648515)),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='name'),
        ),
    ]
